schema = 3

[mod]
  [mod.'github.com/BurntSushi/toml']
    version = 'v1.3.2'
    hash = 'sha256-FIwyH67KryRWI9Bk4R8s1zFP0IgKR4L66wNQJYQZLeg='

  [mod.'github.com/amarbel-llc/go-lib-mcp']
    version = 'v0.0.0-20260211215551-143832b3ba7f'
    hash = 'sha256-y2YROSq+PftzKHUJJrFjSpgkMiPej1JSQTUlIQrDc7c='

  [mod.'github.com/gobwas/glob']
    version = 'v0.2.3'
    hash = 'sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/spf13/cobra']
    version = 'v1.8.0'
    hash = 'sha256-oAE+fEaRfZPE541IPWE0GMeBBYgH2DMhtZNxzp7DFlY='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.5'
    hash = 'sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw='
